from rest_framework.views import exception_handler

def core_exception_handler(exc, context):

    response = exception_handler(exc, context)
    handlers = {
        'NotFound': _handle_not_found_error,
        'ValidationError': _handle_generic_error
    }

    exception_class = exc.__class__.__name__

    if exception_class in handlers:
        # if this requires custom handler,
        # use custom handler
        # otherwise return default handler from above
        return handlers[exception_class](exc, context, response)

    return response

def _handle_generic_error(exc, context, response):
    # take the response generated by DRF & wrap it in the 'error' key
    response.data = {
        'errors': response.data
    }

    return response

def _handle_not_found_error(exc, context, response):
    view = context.get('view', None)

    if view and hasattr(view, 'queryset') and view.queryset is not None:
        error_key = view.queryset.model._meta.verbose_name

        response.data = {
            'errors': {
                error_key: response.data['detail']
            }
        }
    else:
        response = _handle_generic_error(exc, context, response)

    return response
